[package]
name = "step_3_2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "procedural"
proc-macro = true

[dependencies]
quote = "1.0.20"
syn = { version = "1.0.98", features = ["extra-traits"] }
