[package]
name = "step_3_9"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.2.8", features = ["derive", "env"] }
config = "0.13.1"
humantime-serde = "1.1.1"
serde = "1.0.139"
