{
  "mode": {
"debug": false
  },
"server": {
"external_url": "http://127.0.0.1",
"http_port": 8081,
"grpc_port": 8082,
"healthz_port": 10025,
"metrics_port": 9199
  },
"db": {
"mysql": {
"host": "127.0.0.1",
"port": 3306,
"dating": "default",
"user": "root",
"pass": "",
"connections": {
"max_idle": 30,
"max_open": 30
      }
    }
  },
"log": {
"app": {
"level": "info"
    }
  },
"background": {
"watchdog": {
"period": "5s",
"limit": 10,
"lock_timeout": "4s"
    }
  }
}
