[package]
name = "step_3_8"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
slog = "2.7.0"
slog-json = "2.6.1"
slog-scope = "4.4.0"
slog-stdlog = "4.1.1"
slog-term = "2.9.0"
time = "0.3.11"
